name: CI/CD

on: [push]

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.4'
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Run Tests
      run: composer test
    - name: Validate coverage
      run: composer test:coverage -- --min=80