name: CI/CD

on: 
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        volumes:
          - ${{ github.workspace }}/.docker/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql:ro

    steps:

      - uses: actions/checkout@v3

      - name: Wait for MySQL
        run: |
          until mysqladmin ping -h127.0.0.1 -uroot -proot --silent; do
            echo "Waiting for database..."
            sleep 2
          done

      - name: Initialize Database
        run: |
          mysql -h127.0.0.1 -uroot -proot < .docker/initdb.sql
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.4'
          extensions: pdo_mysql, mbstring

      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Wait for MySQL
        run: |
          until mysqladmin ping -h127.0.0.1 -uroot -proot --silent; do
            echo "Waiting for database..."
            sleep 2
          done

      - name: Run Tests
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_NAME: app
          DB_USER: root
          DB_PASS: root
        run: composer test

      - name: Validate coverage
        run: composer test:coverage -- --min=80
